config/routes.rb
Rails.application.routes.draw do
  get 'import/do'
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'import', to: 'import#do'
  post 'import', to: 'import#import'

  get 'monuments', to: 'monuments#index'
  get 'monuments/:id', to: 'monuments#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monument.rb
class Monument < ApplicationRecord
  reverse_geocoded_by :latitude, :longitude
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/import_controller.rb
class ImportController < ApplicationController
  def do

  end

  def import
    if params[:import][:password] != ENV['PASSWORD']
      render 'do'
      flash[:danger] = 'La password inserita non è corretta'
    else
      Monument.delete_all
      endpoint = "https://query.wikidata.org/sparql"
      sparql = '
      SELECT DISTINCT ?item ?itemLabel (AVG(?lat) AS ?lat) (AVG(?lon) AS ?lon) ?image ?wlmid
      WHERE {
        ?item wdt:P2186 ?wlmid ;
                wdt:P17 wd:Q38 ;
                wdt:P625 ?coords.
                ?item                 p:P625         ?statementnode.
                ?statementnode      psv:P625         ?valuenode.
                ?valuenode     wikibase:geoLatitude  ?lat.
                ?valuenode     wikibase:geoLongitude ?lon.
          OPTIONAL { ?item wdt:P18 ?image }
          MINUS { ?item p:P2186 [ pq:P582 ?end ] .
          FILTER ( ?end <= "2018-09-01T00:00:00+00:00"^^xsd:dateTime ) }
        SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],it"  }
      }
      GROUP BY ?item ?itemLabel ?image ?wlmid'

      client = SPARQL::Client.new(endpoint, :method => :get)
      monuments = client.query(sparql)

      for row in monuments do
        @mon = Monument.new
        for key,val in row do
          if key.to_s == 'item'
            itemarray = val.to_s.split('/')
            itemcode = itemarray[4]
            @mon.item = itemcode.to_s
          end
          if key.to_s == 'wlmid'
            @mon.wlmid = val.to_s
          end
          if key.to_s == 'lat'
            @mon.latitude = BigDecimal(val.to_s)
          end
          if key.to_s == 'lon'
            @mon.longitude = BigDecimal(val.to_s)
          end
          if key.to_s == 'itemLabel'
            @mon.itemLabel = val.to_s
          end
          if key.to_s == 'image'
            filename = val.to_s.split('Special:FilePath/')
            @mon.image = filename[1]
          end
        end
        @mon.save
      end
      redirect_to root_path
      flash[:success] = "Import fatto con successo"
    end
  end
end

app/controllers/monuments_controller.rb
class MonumentsController < ApplicationController
  include Pagy::Backend

  def index
    if params[:latitude] && params[:longitude]
      @pagy, @monument = pagy(Monument.near([BigDecimal.new(params[:latitude]), BigDecimal.new(params[:longitude])]))
    elsif params[:city]
      @pagy, @monument = pagy(Monument.near("#{params[:city]}"))
    end
  end

  def show
    @monument = Monument.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/import_helper.rb
module ImportHelper
end

app/helpers/monuments_helper.rb
module MonumentsHelper
  include Pagy::Frontend
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/import/do.html.erb
<%= provide(:title, 'Importazione') %>
<%= form_for(:import, url: import_path, method: :post) do |f| %>
  <div class="control">
  <%= f.label :password, class: 'label'%>
  <%= f.password_field :password, class: 'input' %>
</div>
<%= f.submit 'Esegui import', class: 'button is-danger is-medium' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> - WLM Italia</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.js"   integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="   crossorigin="anonymous"></script>
    <!-- leaflet stuff -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css"
      integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
      crossorigin=""/>
      <script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
      integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="
      crossorigin=""></script>
    <!-- end leaflet stuff -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <% flash.each do |tipo_messaggio, messaggio| %>
      <div class="notification is-<%= tipo_messaggio %>"><%= messaggio %></div>
    <% end %>
    <div class="section">
      <%= yield %>
    </div>
  </body>
    <footer class="footer">
    <p>
    </p>
    <%= link_to 'About', about_path %>
</footer>

</html>

app/views/monuments/index.html.erb
<% provide(:title, 'Monumenti nelle vicinanze') %>
<h1 class="title is-2 is-danger">Lista monumenti nelle vicinanze</h1>
<% if @monument.any? %>
<table class="table">
  <thead>
    <th>Immagine</th>
    <th>Nome</th>
    <th>Link</th>
  </thead>
  <tbody>
      <% @monument.each do |monument| %>
      <tr>
        <td>
        <% if !monument.image.nil? %>
          <%= image_tag "https://commons.wikimedia.org/w/thumb.php?f=#{monument.image}&w=200" , width: 200  %>
        <% else %>
          <%= link_to 'Scattane una tu!',"https://commons.wikimedia.org/w/index.php?title=Special:UploadWizard&campaign=wlm-it&id=#{monument.wlmid}&uselang=it&descriptionlang=it&lat=#{monument.latitude}&lon=#{monument.longitude}&categories=Images+from+Wiki+Loves+Monuments+#{DateTime.now.strftime('%y')}+in+Italy" %>
        <% end %>
        </td>
        <td>
        <%= monument.itemLabel %>
        </td>
        <td>
          <i class="fas fa-search"></i> <%= link_to 'Maggiori informazioni', monuments_path + '/' + monument.id.to_s, class: 'button is-medium is-link'%>
        </td>
      <% end %>
    </tbody>
</table>
  <%== pagy_nav_responsive_bulma(@pagy) %>
<% else %>
<h1 class="is-centered title is-3 is-red">Nessun monumento trovato nella località indicata</h1>
<% end %>
<% if @monument.nil? %>
<h1 class="is-centered title is-3 is-red">Nessun monumento trovato nella località indicata o errore</h1>
<% end %>

app/views/monuments/show.html.erb
<% provide(:title, @monument.itemLabel.capitalize) %>
<h1 class="title is-2 is-primary"><%= @monument.itemLabel.capitalize %></h1>
<!-- map -->
<div id="mapid" class="is-centered" style="height: 360px;"></div>
<script>
var mymap = L.map('mapid').setView([<%= @monument.latitude %>, <%= @monument.longitude %>], 18);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
}).addTo(mymap);

L.marker([<%= @monument.latitude %>, <%= @monument.longitude %>]).addTo(mymap)
    .bindPopup('<%= @monument.itemLabel.capitalize %>')
    .openPopup();
</script>
<!-- end map stuff -->

<br />
   <b>Indirizzo:</b><% result = Geocoder.search([@monument.latitude, @monument.longitude]) %>
    <a href="https://www.openstreetmap.org/?mlat=<%= @monument.latitude %>&mlon=<%= @monument.longitude %>"><%= result.first.address %> </a>
    <hr />
    <br />
    <div class="buttons is-vertical">
      <%= link_to 'Item su Wikidata', "https://wikidata.org/wiki/#{@monument.item}", class: 'button is-danger is-medium' %>
      <br />
      <br />
       <%= link_to ' Carica una foto ', "https://commons.wikimedia.org/w/index.php?title=Special:UploadWizard&campaign=wlm-it&id=#{@monument.wlmid}&uselang=it&descriptionlang=it&lat=#{@monument.latitude}&lon=#{@monument.longitude}&categories=Images+from+Wiki+Loves+Monuments+#{DateTime.now.strftime('%y')}+in+Italy", class: 'button is-primary is-medium' %>
      </div>

app/views/pages/about.html.erb
<%= provide(:title, 'About e privacy policy') %>
<h1>Tool per visualizzare i monumenti partecipanti a <%= link_to 'Wiki Loves Monuments Italia', 'http://wikilovesmonuments.it' %></h1>
<ul>
<li><%= link_to 'Codice sorgente', 'https://github.com/ferdi2005/wikilovesmonuments' %></li>
<li>Dati importati da Wikidata - Licenza CC0 </li></ul>
<li> <%= link_to 'Google Maps privacy policy', 'https://policies.google.com/privacy?hl=it' %></li>
<li>Query di Lorenzo Losa con miglioramenti di Stefano Sabatini</li>
<li>Favicon del sito è il <a href="https://commons.wikimedia.org/wiki/File:Wiki_Loves_Monuments_Logo_notext.svg">Logo ufficiale di WLM</a></li>
</ul>

app/views/pages/home.html.erb
<%= provide(:title, 'Home') %>
<h1 class="is-danger is-2 title is-centered">Wiki Loves Monuments Italia</h1>
<h2 style="position:center;" class="is-link is-4 title is-centered">Ricerca monumenti</h1>
<div class="buttons is-centered">
<form method="get" action="/monuments" id="form-position">
  <input type="hidden" id="latitude" name="latitude"/>
  <input type="hidden" id="longitude" name="longitude"/>
</form>
<button id="click-submit-position" class="button is-primary is-large is-centered">Utilizza la mia posizione</button>
<p id="geoerror" class="is-centered"></p>
</div>
<script>
if (navigator.geolocation) {
    var location_timeout = setTimeout(1000);

    navigator.geolocation.getCurrentPosition(function(position) {
        clearTimeout(location_timeout);

        var lat = position.coords.latitude;
        var lng = position.coords.longitude;

        $("#click-submit-position").click(function(){
          $("#latitude").val(lat);
          $("#longitude").val(lng);
          $("#form-position").submit();
        });

      }, function(error) {
        clearTimeout(location_timeout);
        $("#geoerror").append('Errore di geolocalizzazione! Molto probabilmente non avrai autorizzato la localizzazione dal tuo browser o il tuo browser non ha i permessi necessari. Scrivi il nome della città nel campo sotto.');
        $("#click-submit-position").addClass('is-hidden');
    });
} else {
    // Fallback for no geolocation
    $("#geoerror").append('Errore di geolocalizzazione! Molto probabilmente non avrai autorizzato la localizzazione dal tuo browser o il tuo browser non ha i permessi necessari. Scrivi il nome della città nel campo sotto.');
    $("#click-submit-position").addClass('is-hidden');
}

</script>
<div class="strike">
   <span>O</span>
</div>
<br />
<script>
function empty() {
    var x;
    x = document.getElementById("searchTextField").value;
    if (x == "") {
        alert("Inserisci il nome di una città prima di cercare.");
        return false;
    };
}
</script>
<form method="get" action="/monuments" >
  <div class="field has-addons is-centered">
      <div class="control">
        <input type="text" class="input" id="searchTextField" placeholder="Città" name="city"></input>
      </div>
      <div class="control">
        <button type="submit" class="button is-primary" placeholder="Cerca" id="click-form" onClick="return empty()">Cerca</button>
      </div>
  </div>
</br>
</form>
<% maps_api_key = ENV['GOOGLE_MAPS_API_KEY'] %>
<script src='https://maps.googleapis.com/maps/api/js?key=<%= maps_api_key %>&libraries=places'></script>
<script>
  function initialize() {
    var options = {
      types: ['(cities)'],
      componentRestrictions: {
        country: "it"
      }
    };

    var input = document.getElementById('searchTextField');
    var autocomplete = new google.maps.places.Autocomplete(input, options);
  }

  google.maps.event.addDomListener(window, 'load', initialize);
</script>